//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobsonLibrary.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DobsonLibrary.DataAccess.SQLQueries", typeof(SQLQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  a.answerid,
        ///              a.answerstring,
        ///              a.queryid,
        ///              a.realmid
        ///FROM    Answer A
        ///ORDER BY a.answerid.
        /// </summary>
        internal static string getAllAnswersQuery {
            get {
                return ResourceManager.GetString("getAllAnswersQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT classid,name FROM class.
        /// </summary>
        internal static string getAllContextClassesMorpheus3DB {
            get {
                return ResourceManager.GetString("getAllContextClassesMorpheus3DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id,lex FROM nodes WHERE lex LIKE &apos;%/classes#%&apos;.
        /// </summary>
        internal static string getAllContextClassesQuery {
            get {
                return ResourceManager.GetString("getAllContextClassesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  q.queryid,
        ///              q.querystring,
        ///              q.realmid
        ///FROM    Query q
        ///ORDER BY q.queryid.
        /// </summary>
        internal static string getAllQueriesQuery {
            get {
                return ResourceManager.GetString("getAllQueriesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  r.realm,
        ///              r.realmid
        ///FROM    Realm r
        ///ORDER BY r.realm.
        /// </summary>
        internal static string getAllRealmsQuery {
            get {
                return ResourceManager.GetString("getAllRealmsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT     s.searchID,
        ///           s.searchEngine,
        ///           s.searchString,
        ///           p.entryOrder,
        ///           w.url
        ///FROM       Search s
        ///INNER JOIN PathEntry p
        ///ON         p.searchID = s.searchID
        ///INNER JOIN Website w
        ///ON         p.websiteID = w.websiteID
        ///ORDER BY   s.searchId,
        ///           p.entryOrder.
        /// </summary>
        internal static string getAllSearchesQuery {
            get {
                return ResourceManager.GetString("getAllSearchesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  contextname,
        ///              contextid
        ///FROM    context
        ///ORDER BY contextid.
        /// </summary>
        internal static string getContextQuery {
            get {
                return ResourceManager.GetString("getContextQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT    DISTINCT  w.url
        ///FROM       Website w
        ///INNER JOIN PathEntry p
        ///ON         p.websiteId = w.websiteID
        ///INNER JOIN Search s
        ///ON         p.searchID = s.searchID
        ///INNER JOIN SearchKeyword ks
        ///ON         ks.searchID = s.searchID
        ///INNER JOIN Keyword k
        ///ON         k.keywordID = ks.keywordID
        ///.
        /// </summary>
        internal static string getFilteredWebsitesQuery {
            get {
                return ResourceManager.GetString("getFilteredWebsitesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) AS keywordCount
        ///FROM   Keyword
        ///WHERE  keywordString = :keywordString.
        /// </summary>
        internal static string getKeywordCountQuery {
            get {
                return ResourceManager.GetString("getKeywordCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT keywordId
        ///FROM   Keyword
        ///WHERE  keywordString = :keywordString.
        /// </summary>
        internal static string getKeywordIdQuery {
            get {
                return ResourceManager.GetString("getKeywordIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CURRVAL(&apos;answer_answerid_seq&apos;) AS lastVal
        ///             FROM Answer.
        /// </summary>
        internal static string getLastAnswerIdQuery {
            get {
                return ResourceManager.GetString("getLastAnswerIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT max(highlightid) AS lastVal
        ///             FROM highlight.
        /// </summary>
        internal static string getLastHighlightIdQuery {
            get {
                return ResourceManager.GetString("getLastHighlightIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CURRVAL(&apos;contextinstance_contextinstid_seq&apos;) AS lastVal
        ///             FROM Individual.
        /// </summary>
        internal static string getLastIndividualIdQuery {
            get {
                return ResourceManager.GetString("getLastIndividualIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT max(inputid) AS lastID
        ///             FROM input.
        /// </summary>
        internal static string getLastInputIdQuery {
            get {
                return ResourceManager.GetString("getLastInputIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT max(pageid) as lastVal
        ///             FROM Page.
        /// </summary>
        internal static string getLastPageIdQuery {
            get {
                return ResourceManager.GetString("getLastPageIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT max(pagerefid) as lastVal
        ///             FROM PageReference.
        /// </summary>
        internal static string getLastPageReferenceIdQuery {
            get {
                return ResourceManager.GetString("getLastPageReferenceIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  max(phraseid) as lastVal
        ///             FROM Phrase.
        /// </summary>
        internal static string getLastPhraseIdQuery {
            get {
                return ResourceManager.GetString("getLastPhraseIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CURRVAL(&apos;query_queryid_seq&apos;) AS lastVal
        ///             FROM query.
        /// </summary>
        internal static string getLastQueryIdQuery {
            get {
                return ResourceManager.GetString("getLastQueryIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CURRVAL(&apos;realm_realmid_seq&apos;) AS lastVal
        ///             FROM realm.
        /// </summary>
        internal static string getLastRealmIdQuery {
            get {
                return ResourceManager.GetString("getLastRealmIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CURRVAL(&apos;search_searchid_seq&apos;) AS lastVal
        ///             FROM Search.
        /// </summary>
        internal static string getLastSearchIdQuery {
            get {
                return ResourceManager.GetString("getLastSearchIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  COUNT(*) AS websiteCount
        ///FROM    Website
        ///WHERE  url = :url.
        /// </summary>
        internal static string getWebsiteCountQuery {
            get {
                return ResourceManager.GetString("getWebsiteCountQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT websiteId
        ///FROM   Website
        ///WHERE  url = :url.
        /// </summary>
        internal static string getWebsiteIdQuery {
            get {
                return ResourceManager.GetString("getWebsiteIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO QueryHas
        ///                      (
        ///                          answerid,
        ///                          individualid,
        ///                          io
        ///                      )
        ///VALUES         (
        ///                          :answerid,
        ///                          :individualid,
        ///                          :io
        ///                      ).
        /// </summary>
        internal static string insertAnswerHasQuery {
            get {
                return ResourceManager.GetString("insertAnswerHasQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Answer
        ///                      (
        ///                          answerstring,
        ///                          queryid,
        ///                          realmid                      
        ///)
        ///VALUES         (
        ///                         :answerstring,
        ///                         :queryid,
        ///                         :realmid
        ///                     ).
        /// </summary>
        internal static string insertAnswerQuery {
            get {
                return ResourceManager.GetString("insertAnswerQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO class
        ///                      (
        ///                          classid,
        ///                          contextid,
        ///                          name
        ///                      )
        ///VALUES         (
        ///                          :classid,
        ///                          :contextid,
        ///                          :name
        ///                      ).
        /// </summary>
        internal static string insertContextClassQuery {
            get {
                return ResourceManager.GetString("insertContextClassQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Context
        ///                     (
        ///                     contextname
        ///                     )
        ///VALUES
        ///                     (
        ///                     :contextname
        ///                     )
        ///                  
        ///
        ///
        ///.
        /// </summary>
        internal static string insertContextQuery {
            get {
                return ResourceManager.GetString("insertContextQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HasModifier(
        ///              individualid
        ///)VALUES(
        ///             :individualid
        ///)
        ///.
        /// </summary>
        internal static string insertHasModifierQuery {
            get {
                return ResourceManager.GetString("insertHasModifierQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Highlight
        ///                     (
        ///                     highlightid,
        ///                     answerID,
        ///                     classid,
        ///                     beginoffset,
        ///                     endoffset,
        ///                     queryid,
        ///                     startxpath,
        ///                     endxpath,
        ///                     timestamp,
        ///                     url,
        ///                     pagesource,
        ///                     meetpoint
        ///                     )
        ///VALUES
        ///                    (
        ///                    : [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string insertHighlightQuery {
            get {
                return ResourceManager.GetString("insertHighlightQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Individual
        ///                      (
        ///                          phraseid,
        ///                          classid
        ///                      )
        ///VALUES         (
        ///                          :phraseid,
        ///                          :classid
        ///                      ).
        /// </summary>
        internal static string insertIndividualQuery {
            get {
                return ResourceManager.GetString("insertIndividualQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Input
        ///           (
        ///              inputid,
        ///               name,
        ///               pageRefId,
        ///               classId,
        ///               individualid,
        ///              highlightid
        ///            )
        ///VALUES  (
        ///               :inputid,
        ///               :name,
        ///               :pageRefId,
        ///               :classId,
        ///               :individualid,
        ///               :highlightid
        ///             )           .
        /// </summary>
        internal static string insertInputQuery {
            get {
                return ResourceManager.GetString("insertInputQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Keyword
        ///                      (
        ///                          keywordString
        ///                      )
        ///VALUES         (
        ///                         :keywordString
        ///                     ).
        /// </summary>
        internal static string insertKeywordQuery {
            get {
                return ResourceManager.GetString("insertKeywordQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Modifier
        ///               (
        ///               modifierstring,
        ///               rank
        ///)VALUES(
        ///               :modifierstring,
        ///               :rank
        ///).
        /// </summary>
        internal static string insertModifierQuery {
            get {
                return ResourceManager.GetString("insertModifierQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Page
        ///                      (
        ///                          baseurl,
        ///                          pageid
        ///                      )
        ///VALUES         (
        ///                          :baseurl,
        ///                          :pageid
        ///                      ).
        /// </summary>
        internal static string insertPageQuery {
            get {
                return ResourceManager.GetString("insertPageQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PageReference
        ///                      (
        ///                          querystring,
        ///                          pageid,
        ///                          queryid,
        ///                          pagerefid,
        ///                          timestamp,
        ///                          pagesrc,
        ///                          formxpath,
        ///                          destinationUrl
        ///                      )
        ///VALUES         (
        ///                          :querystring,
        ///                          :pageid,
        ///                          :queryid,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string insertPageReferenceQuery {
            get {
                return ResourceManager.GetString("insertPageReferenceQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO PathEntry
        ///                      (
        ///                          searchId,
        ///                          websiteId,
        ///                           entryOrder
        ///                      )
        ///VALUES          (
        ///                          :searchId,
        ///                          :websiteId,
        ///                          :entryOrder
        ///                      ).
        /// </summary>
        internal static string insertPathEntryQuery {
            get {
                return ResourceManager.GetString("insertPathEntryQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO phrasebelongstocontext
        ///                      (
        ///                          contextid,
        ///                          phraseid
        ///                      )
        ///VALUES         (
        ///                          :contextid,
        ///                          :phraseid
        ///                      ).
        /// </summary>
        internal static string insertPhraseBelongsToContextQuery {
            get {
                return ResourceManager.GetString("insertPhraseBelongsToContextQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Phrase
        ///                      (
        ///                          phrasestring,
        ///                          phraseid
        ///                      )
        ///VALUES         (
        ///                          :phrasestring,
        ///                          :phraseid
        ///                      ).
        /// </summary>
        internal static string insertPhraseQuery {
            get {
                return ResourceManager.GetString("insertPhraseQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO QueryHas
        ///                      (
        ///                          queryid,
        ///                          individualid,
        ///                          io
        ///                      )
        ///VALUES         (
        ///                          :queryid,
        ///                          :individualid,
        ///                          :io
        ///                      ).
        /// </summary>
        internal static string insertQueryHasQuery {
            get {
                return ResourceManager.GetString("insertQueryHasQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Query
        ///                      (
        ///                          querystring,
        ///                          realmid,
        ///                          userID
        ///                      )
        ///VALUES         (
        ///                         :querystring,
        ///                         :realmid,
        ///                         :userID
        ///                     ).
        /// </summary>
        internal static string insertQueryQuery {
            get {
                return ResourceManager.GetString("insertQueryQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Realm
        ///                      (
        ///                          realm
        ///                      )
        ///VALUES         (
        ///                          :realm
        ///                      )
        ///.
        /// </summary>
        internal static string insertRealmQuery {
            get {
                return ResourceManager.GetString("insertRealmQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO SearchKeyword
        ///            (
        ///                 SearchId,
        ///                 keywordId
        ///            )
        ///VALUES      (
        ///                 :searchId,
        ///                 :keywordId
        ///            ).
        /// </summary>
        internal static string insertSearchKeywordQuery {
            get {
                return ResourceManager.GetString("insertSearchKeywordQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Search
        ///                      (
        ///                          searchEngine,
        ///                          searchString
        ///                      )
        ///VALUES         (
        ///                          :searchEngine,
        ///                          :searchString
        ///                     ).
        /// </summary>
        internal static string insertSearchQuery {
            get {
                return ResourceManager.GetString("insertSearchQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Website
        ///                      (
        ///                          url
        ///                      )
        ///VALUES         (
        ///                         :url
        ///                     ).
        /// </summary>
        internal static string insertWebsiteQuery {
            get {
                return ResourceManager.GetString("insertWebsiteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE PageReference
        ///SET querystring = :querystring
        ///WHERE pagerefid = :pagerefid.
        /// </summary>
        internal static string updatePageReferenceQuerystring {
            get {
                return ResourceManager.GetString("updatePageReferenceQuerystring", resourceCulture);
            }
        }
    }
}
